### ISSUE TITLE
Must handle streams and null file.contents

### ISSUE THREAD

**Issue by phated** [sindresorhus/gulp-template#2]
Currently, you are always replacing the `file.contents` with a Buffer.  You need to handle a streaming or `null` `file.contents`.  Handling streams is outlined [here](https://github.com/wearefractal/gulp/wiki/Writing-a-gulp-plugin#dealing-in-streams) and I handle each type in [gulp-jade](https://github.com/phated/gulp-jade/blob/master/index.js#L30-L49) for an example.

**Comment by joaomilho** [comment]
Just stumbled on this today, and the reference that supposedly fixes it on gulp util says "Changed my mind, not doing this". So what is the solution for a stream?

**Comment by kevva** [comment]
@joaomilho, [this](https://github.com/sindresorhus/gulp-template/blob/master/index.js#L14-L17).

**Comment by joaomilho** [comment]
@kevva , this is actually the problem. My solution was to use vinyl-source-buffer instead of vinyl-source-stream.

**Comment by kevva** [comment]
This issue wasn't about stream support, but handling cases where streams where used but not handled.
