### ISSUE TITLE
Silent ignore missing variables

### ISSUE THREAD

**Issue by litchfield** [sindresorhus/gulp-template#25]
I'd like to be able to pass "silent: true" into options, to silently ignore missing variables (perhaps with a warning printed, but no exception).

**Comment by sindresorhus** [comment]
Why?

**Comment by litchfield** [comment]
Optional variables. And in some cases, gulp "not crashing" is more important that having a missing variable merge.

**Comment by kevva** [comment]
If gulp not crashing is important to you should have a look at https://github.com/floatdrop/gulp-plumber.

**Comment by litchfield** [comment]
Er, thanks but no thanks, @kevva. I'll just fork it.

**Comment by anupkumarsharma** [comment]
I think the request sounds legit. Its just an extensiblity ask?
