### ISSUE TITLE
Plugin silently fail when a variable is missing

### ISSUE THREAD

**Issue by lorem--ipsum** [sindresorhus/gulp-template#27]
Hey, first of all thanks for this useful plugin :-)

I've found that when including a variable not present in the data, the plugin silently stops working... Any hint ?

**Comment by sindresorhus** [comment]
What does "stop working" mean?

As you can see from the code https://github.com/sindresorhus/gulp-template/blob/master/index.js we're pretty much just passing your string and data to the Lodash template function. So I doubt the problem is with this plugin.

**Comment by lorem--ipsum** [comment]
Hmm okay. Thanks !
