### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by fernandofas** [sindresorhus/gulp-template#31]
Hi there,

I installed gulp-template and followed the instructions, but seems like there is an issue as the gulpfile.js is not generated and because of this issue, I can't use it.

Any idea why this is happening or is missing some instructions?

https://github.com/sindresorhus/gulp-template

Also, when you posted:

Usage

src/greeting.html

<h1>Hello <%= name %></h1>
It does not mean anything to me as I can't find the gulpfile.js.

Cheers,

fernando fas
fernandofas@gmail.com

**Comment by SamVerschueren** [comment]
You have to write your `gulpfile.js` yourselves. This is just a plugin to parse a template file like this:

```html
<h1>Hello <%= name %></h1>
```

To an output file like

```html
<h1>Hello Sindre</h1>
```

Please read the [getting started](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) guide of Gulp first.
