### ISSUE TITLE
Change interpolation 

### ISSUE THREAD

**Issue by yairEO** [sindresorhus/gulp-template#34]
how can I do that? 
The README has no example for messing with the internal settings of the template engine

Thanks

**Comment by sindresorhus** [comment]
The options are linked to right in the readme: https://github.com/sindresorhus/gulp-template#options

**Comment by yairEO** [comment]
Sorry, missed that one. I was mostly looking at examples and I was like `where is the example where he pass settings.. hmmmmm...` 

Thank you for answering so quickly!
